apiVersion: v1
kind: Service
metadata:
  name: matches-service
  labels:
    app: maches
spec:
  type: NodePort
  selector:
    app: matches
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080